[package]
name = "gswww"
version = "1.1.0"
authors = ["Ph1ll"]
description = "a Graphical Solution to your Wayland Wallpaper Woes"
edition = "2021"
license = "MIT"
readme="README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.6.6", package = "gtk4" }
